issuer_common_name: Issuer CA
ca_key_file: key.pem
key_file: key.pem
cert_file: cert.pem
output:
  power.conf: |
    [Result]
    EQUAL,{cert_signature},65537,trusted_root_modulus->{result}

data:
  user_id: fd974345-6bfd-4227-9b92-96d49313d312
